/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AuthRouteImport } from "./routes/auth"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AppChannelsServerIdChannelIdRouteImport } from "./routes/_app/channels.$serverId.$channelId"

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsServerIdChannelIdRoute =
  AppChannelsServerIdChannelIdRouteImport.update({
    id: "/channels/$serverId/$channelId",
    path: "/channels/$serverId/$channelId",
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/auth": typeof AuthRoute
  "/channels/$serverId/$channelId": typeof AppChannelsServerIdChannelIdRoute
}
export interface FileRoutesByTo {
  "/auth": typeof AuthRoute
  "/": typeof AppIndexRoute
  "/channels/$serverId/$channelId": typeof AppChannelsServerIdChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/auth": typeof AuthRoute
  "/_app/": typeof AppIndexRoute
  "/_app/channels/$serverId/$channelId": typeof AppChannelsServerIdChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/auth" | "/channels/$serverId/$channelId"
  fileRoutesByTo: FileRoutesByTo
  to: "/auth" | "/" | "/channels/$serverId/$channelId"
  id:
    | "__root__"
    | "/_app"
    | "/auth"
    | "/_app/"
    | "/_app/channels/$serverId/$channelId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/channels/$serverId/$channelId": {
      id: "/_app/channels/$serverId/$channelId"
      path: "/channels/$serverId/$channelId"
      fullPath: "/channels/$serverId/$channelId"
      preLoaderRoute: typeof AppChannelsServerIdChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppChannelsServerIdChannelIdRoute: typeof AppChannelsServerIdChannelIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppChannelsServerIdChannelIdRoute: AppChannelsServerIdChannelIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
